(define (deep-reverse items)
  (define (iter-reverse z result)
    (cond ((null? z) result)
          ((not (pair? z)) (newline) (display z) z)
          (else (newline) (display z) (iter-reverse (cdr z) (cons (iter-reverse (car z) '()) result)))
    )
  )
  (iter-reverse items '())
)
