(define (make-rectangle-with-adjacent-segments l1 l2)
  (cons l1 l2)
)

(define (rectangle-area r)
  (* (segment-length (car r)) (segment-length (cdr r)))
)
(define (rectangle-perimeter r)
  (* (+ (segment-length (car r)) (segment-length (cdr r))) 2)
)

(define (segment-length l)
  (sqrt (+ (square (- (x-point (start-segment l)) (x-point (end-segment l))))
    (square (- (y-point (start-segment l)) (y-point (end-segment l)))))))
(define pi (* 4 (atan 1)))
;auxilliary procedures needed for points and segments
(define (square x) (* x x))
(define (make-point x y) (cons x y))
(define (x-point p) (car p))
(define (y-point p) (cdr p))
(define (print-point p) (newline)
(display "(") (display (x-point p)) (display ",")
(display (y-point p)) (display ")"))
(define (make-segment p1 p2) (cons p1 p2))
(define (start-segment l) (car l))
(define (end-segment l) (cdr l))
(define (midpoint-segment l)
  (make-point
    (/ (+ (x-point (start-segment l)) (x-point (end-segment l))) 2)
    (/ (+ (y-point (start-segment l)) (y-point (end-segment l))) 2)
  )
)
