(define (make-account bal password)
  (define (withdraw amount)
    (cond ((> amount bal) "Insufficient funds")
          (else (set! bal (- bal amount)) bal)))
  (define (deposit pwd amount)
    (set! bal (+ bal amount)))
  (define (dispatch string m)
    (cond ((not (eq? string password)) (lambda (x) "Incorrect password"))
          ((eq? m 'withdraw) withdraw)
          ((eq? m 'deposit) diposit)
          (else (error "Unknown request -- MAKE-ACCOUNT" m))))
  dispatch)
