(define (make-joint orig-acc orig-pass new-pass)
  (let ((wrong-pawd-count 0))
    (define (dispatch string m)
      (cond ((not (eq? string new-pass))
              (set! wrong-pawd-count (+ wrong-pawd-count 1))
              (if (> wrong-pawd-count 7)
                  call-the-cops
                  (lambda (x) "Incorrect Password")))
             (else (set! wrong-pawd-count 0) (orig-acc orig-pass m))))
     dispatch))

(define (make-account bal password)
  (define (withdraw amount)
    (cond ((> amount bal) "Insufficient funds")
          (else (set! bal (- bal amount)) bal)))
  (define (deposit amount)
    (set! bal (+ bal amount)) bal)
    (let ((wrong-pawd-count 0))
      (define (dispatch string m)
        (cond ((not (eq? string password))
                (set! wrong-pawd-count (+ wrong-pawd-count 1))
                (if (> wrong-pawd-count 7)
                    call-the-cops
                    (lambda (x) "Incorrect Password")))
              ((eq? m 'withdraw) (set! wrong-pawd-count 0) withdraw)
              ((eq? m 'deposit) (set! wrong-pawd-count 0) deposit)
              (else (error "Unknown request -- MAKE-ACCOUNT" m))))
              dispatch))

(define (call-the-cops amt) "siren....")
