(define (make-account bal password)
  (define (withdraw amount)
    (cond ((> amount bal) "Insufficient funds")
          (else (set! bal (- bal amount)) bal)))
  (define (deposit pwd amount)
    (set! bal (+ bal amount)))
    (let ((wrong-pawd-count 0))
      (define (dispatch string m)
        (cond ((not (eq? string password))
                (set! wrong-pawd-count (+ wrong-pawd-count 1))
                (if (> wrong-pawd-count 7)
                    call-the-cops
                    (lambda (x) "Incorrect Password")))
              ((eq? m 'withdraw) (set! wrong-pawd-count 0) withdraw)
              ((eq? m 'deposit) (set! wrong-pawd-count 0) deposit)
              (else (error "Unknown request -- MAKE-ACCOUNT" m))))
              dispatch))

(define (call-the-cops amt) "siren....")
